version: '3'
services:
  #PHP Service
  app:
    build:
      context: ./php
    image: php:8.1-fpm
    restart: unless-stopped
    tty: true
    working_dir: /var/www/${SRC_PATH}
    volumes:
      - ../${SRC_PATH}:/var/www/${SRC_PATH}:cached
      - ./php/php8.1.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network
  #Nginx Service
  webserver:
    image: nginx:alpine
    depends_on:
      - app
    restart: unless-stopped
    tty: true
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ../${SRC_PATH}:/var/www/${SRC_PATH}
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - /var/www/certbot/:/var/www/certbot/:ro
      - ~/certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - app-network
  #MySQL Service
  db:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql/
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network
  certbot:
    image: certbot/certbot:latest
    profiles: ["certbot"]
    depends_on:
      - webserver
    volumes:
      - /var/www/certbot/:/var/www/certbot/:rw
      - ~/certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email ${ADMIN_EMAIL} --agree-tos --no-eff-email --force-renewal -d ${DOMAIN} -d www.${DOMAIN}
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local